### PR TITLE
chore(gh-actions/go-releaser): #166. Update/Automate release process

### PR DESCRIPTION
**Pull request by mike-winberry**
## Description
Currently the release process consists of manual tag creation and pushing. This triggers a github workflow to create and publish a release using the github-native changelog options in go-releaser. In order to help automate and provide some additional review checks, the .go-releaser.yaml should be updated to create a draft release rather than releasing automatically, so it can be reviewed prior to release. In addition, the workflow should be enhanced or supplemented to generate a tag when a PR is merged and kick off a draft release automatically, bumping the version to patch or minor following [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) guidelines. 

- add release-please to the release yaml
- add commitlint for pr title linting
- update go-releaser to create draft

...

## Related Issue
relates to #166 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/go-oscal/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

**Comment by brandtkeller** [comment]
@mike-winberry Are there any modification to the release documentation that need to modified for this process?

**Comment by mike-winberry** [comment]
> @mike-winberry Are there any modification to the release documentation that need to modified for this process?

Yes, release-process notes should now be updated!

**Review by brandtkeller — DISMISSED** [review]
I'm liking the direction this is heading for team release processes.

**Comment by mike-winberry** [comment]
> I'm liking the direction this is heading for team release processes.

Will need a re-review. I updated with a release-please-config.json that is configured to prevent major bumps pre v1.0.0. So breaking will kickoff minor and non-breaking patches.

**Review by brandtkeller — APPROVED** [review]

**Pull request merged**
