### PR TITLE
feat(generate): structure for ordered keys

### LINKED ISSUE #240: Ability to establish known struct key order
### Is your feature request related to a problem? Please describe.
Order of the fields in tooling that consumes go-oscal was mentioned as a point of confusion for the generation of artifacts. Would like to test if it is possible to define ordered structs for the top level models. 

### Describe the solution you'd like

- **Given** Generation of a model
- **When** a new model is written to a file
- **Then** the order of the model fields is deterministic and ordered as intended

### Describe alternatives you've considered
non-critical change

### Additional context
Establish some error checking to ensure we capture drift when model is updated with new or different fields.

### PR DESCRIPTION
**Pull request by brandtkeller**
## Description

During a recent webinar - the formatting of OSCAL documents in Lula with regards to field order was mentioned as a point of confusion. While we do not want to stray far from the current generation logic which has no strict ties to order - providing the order of elements for the top-level models may clear up structure. 

Recommend just the top-level models - open to feedback on ensuring we have error catching for non-deeply-equal items. 

## Related Issue

Fixes #240

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/go-oscal/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

**Comment by mike-winberry** [comment]
highly recommend taking a look at libraries, because I don't think maintaining a map of the fields is gonna be a good long term solution, it puts us back to needing dev intervention for schema changes, we should be able to either maintain OG file order, which would be the computationally least complex solution I think, I had looked into this a month or two ago and had a partial solution using either https://github.com/elliotchance/orderedmap or some similar solution https://github.com/defenseunicorns/go-oscal/compare/main...163-revise-fields-in-random-order-after-revision

**Comment by mike-winberry** [comment]
https://github.com/defenseunicorns/go-oscal/issues/163

^The original issue.

**Comment by mike-winberry** [comment]
also here is where we are sorting alphabetically, https://github.com/defenseunicorns/go-oscal/blob/6b94a9098f062b51a74477501f4ba5f4e430b164/src/internal/generate/generate.go#L167, idk if removing this would maintain the schema order, because I think that could depend on the marshal/unmarshalling method as well as the golang [map](https://go.dev/blog/maps) ordering

**Comment by brandtkeller** [comment]
> highly recommend taking a look at libraries, because I don't think maintaining a map of the fields is gonna be a good long term solution, it puts us back to needing dev intervention for schema changes, we should be able to either maintain OG file order, which would be the computationally least complex solution I think, I had looked into this a month or two ago and had a partial solution using either https://github.com/elliotchance/orderedmap or some similar solution [main...163-revise-fields-in-random-order-after-revision](https://github.com/defenseunicorns/go-oscal/compare/main...163-revise-fields-in-random-order-after-revision)

> also here is where we are sorting alphabetically,
> 
> https://github.com/defenseunicorns/go-oscal/blob/6b94a9098f062b51a74477501f4ba5f4e430b164/src/internal/generate/generate.go#L167
> 
> , idk if removing this would maintain the schema order, because I think that could depend on the marshal/unmarshalling method as well as the golang [map](https://go.dev/blog/maps) ordering

All great items for context - I don't disagree that maintaining the map fields is not a great long term solution. Removing the sort results in the randomized output result with regards to order. Curious if there is another angle to approach this from - but that may be unnecessary work - the fields in the schema are listed alphabetically.

Overall just wanted to validate marshalling oscal models with fields in a specific order to validate they appear as expected. Generate is an operation that we seldomly run (IE going on 6 months since last OSCAL release). Curious how revise would respond coupled with this. 

Overall not a pressing need -> more of an experiment to evaluate.

**Comment by mike-winberry** [comment]
could we just use the schema order (may need to back fix the doctor command to maintain the schema order), but since the schema is xml derived it may actually make sense they are ordered, [ ] will verify in the xml. In that case we wouldn't need to worry about hardcoding, and could pull the order directly from the schema applicable to the oscal document. thoughts?

**Comment by brandtkeller** [comment]
Closing pull request as we orient to review metaschema for generation.

**Pull request closed without merging**
