### PR TITLE
fix(generate)!: embedded optional structs changed to pointers

### PR DESCRIPTION
**Pull request by mike-winberry**
## Description
When marshalling and unmarshalling json documents, fields with the tag `omitempty` were being instantiated and lingering in the document. In order to resolve this generate has been updated to add `*` indicating a pointer for all non-required fields. 

- fix(generate)!: now uses pointers for optional fields.
  - effects all existing types. 
  - Ignores primitives. 

## Related Issue
#131 

## Type of change
- [x] Breaking bug fix.

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/go-oscal/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

**Comment by mike-winberry** [comment]
Created test lula branch with the updates applied and tests passing as example of how the changes would effect lula.
https://github.com/defenseunicorns/lula/tree/test_go-oscal_pointers

**Comment by mike-winberry** [comment]
Lula test PR: https://github.com/defenseunicorns/lula/pull/317

**Comment by brandtkeller** [comment]
Reviewing this more and reading through a [proposal](https://github.com/golang/go/issues/11939) that helps me understand the implications here and why pointers are required.

**Comment by mike-winberry** [comment]
Bumping back to draft to handle #174 as part of this PR.

**Review by brandtkeller — APPROVED** [review]
Now is the best time to make these adjustments. Appreciate the ADR around the decision.

**Pull request merged**
