### PR TITLE
Feat: Add uuid generation functions for library use

### PR DESCRIPTION
**Pull request by brandtkeller**
Simple UUID generation logic for use by downstream consumers. Should we want to change to a specific implementation of UUID generation - this would allow use to have a source of truth versus implementations in each tool. 

I intend this to be used in Lula for both UUID creation as well as UUID generation in the command line for OSCAL developers.

### CODE REVIEW

**Comment by brandtkeller** [comment]
Closes #41

**Review by Alvin-zzz — APPROVED** [review]
This is great, will help workflow for ease of use down the line. Specially with control changes/additions.

**Comment by CloudBeard** [comment]
Awesome work! Tested locally too no issues on my end.

**Review by CloudBeard — APPROVED** [review]
Awesome work! Tested locally too no issues on my end.

**Comment by brandtkeller** [comment]
> Awesome work! Tested locally too no issues on my end.

@CloudBeard I mean... you wrote this 😆 - I'm just putting it somewhere to begin to standardize and establish a source of truth.

**Review by mike-winberry — APPROVED** [review]

**Pull request merged**
