### PR TITLE
chore(actions): fix code scanning alerts

### PR DESCRIPTION
**Pull request by mike-winberry**
## Description
- [x] fix(commitlint): dangerous workflow following guide at https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
- [x] fix(unit-test):  token permission #233 
- [x] fix(release):  missing top level permissions #235 
- [x] fix(commitlint): missing top level permissions #236  
- [x] fix(release): set write permissions at job level and contents to read at top level 
- [x] fix(commitlint): #239 pinned commitlint dependencies
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/go-oscal/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

**Review by CloudBeard — APPROVED** [review]

**Review by CloudBeard — COMMENTED** [review]
I think you're only missing 1 https://github.com/defenseunicorns/go-oscal/security/code-scanning/19

Everything is solid!

**Comment by mike-winberry** [comment]
> I think you're only missing 1 [Token-Permissions](/defenseunicorns/go-oscal/security/code-scanning/19)
> 
> Everything is solid!

Not sure whats the issue with that one, the top level is set to read, and only the jobs that need write have write.

**Comment by CloudBeard** [comment]
That is true, I thought it was for packages not content. 

I thought it was asking for packages like below, but now idk lol.

```yaml
name: Publish Go-OSCAL Packages on Tag

permissions:
  contents: read
  packages: read

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      # Checkout the repo and setup the tooling for this job
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
111

**Review by CloudBeard — APPROVED** [review]

**Comment by mike-winberry** [comment]
> That is true, I thought it was for packages not content.
> 
> I thought it was asking for packages like below, but now idk lol.
> 
> ```yaml
> name: Publish Go-OSCAL Packages on Tag
> 
> permissions:
>   contents: read
>   packages: read
> 
> on:
>   push:
>     tags:
>       - "v*"
> 
> jobs:
>   build:
>     runs-on: ubuntu-latest
>     permissions:
>       packages: write
>     steps:
>       # Checkout the repo and setup the tooling for this job
>       - name: Checkout
>         uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
>         with:
>           fetch-depth: 0
> 111
> ```

Ill try this and push

**Review by brandtkeller — APPROVED** [review]

**Pull request merged**
