### PR TITLE
150 release add workflow to create an update changelog pr after release

### PR DESCRIPTION
**Pull request by mike-winberry**
- Created workflow to update the changelog in accordance with keep-a-changelog after release.
- Updated the current changelog to be of correct formatting and added all releases. 
- Create docs/updating-changelog for information on updating the changelog. 

### Redirect:
- look into current tools like go-releaser to manage the changelog. 
- checkout other open source co-projects and handle in a similar method. 
- go-releaser behind paywall.
- Current OSS pattern does not include changelog for pepr, zarf, leapfrogai. 
- do we want to go with release-please flow? or scrap to follow suit with our other projects. 
- https://goreleaser.com/customization/changelog/

### CODE REVIEW

**Comment by mike-winberry** [comment]
see https://github.com/mike-winberry/Test-actions.git repo for example releases and PRS

**Comment by mike-winberry** [comment]
Example Test release:
Uploading Screen Recording 2024-03-04 at 6.49.00 AM.mov…

**Comment by mike-winberry** [comment]
https://github.com/defenseunicorns/go-oscal/assets/86802655/63e0be23-081b-4787-811e-31d0b31c0e37

**Comment by brandtkeller** [comment]
Question - would we potentially want the Changelog to have the information about a released version _before_ we cut the release? IE as a step in the release process.

If you were to select a tagged release (source code, or the tag in the repo) the Changelog would still say 'unreleased' as the PR followed the TAG creation yes?

**Comment by CloudBeard** [comment]
I think Goreleaser can show that information with a template but you have to pay to use templates. Couldn't find a good example of it being done quickly.

**Comment by mike-winberry** [comment]
bumping to draft in favor of go-releaser and other automated tools to generate the changelog.

**Comment by mike-winberry** [comment]
Closing for now until, consensus on wether or not we should bother with a changelog, or follow the release-pls pattern.

**Pull request closed without merging**
